package id.kalender.hijriah;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.os.*;import android.view.*;import android.widget.*;import com.batoulapps.adhan.PrayerTimes;import java.time.*;import java.time.chrono.HijrahDate;import java.time.format.DateTimeFormatter;import java.time.temporal.*;import java.util.*;

public class MainActivity extends Activity {
 private static final String[] HM={"Muharam","Safar","Rabiulawal","Rabiulakhir","Jumadilawal","Jumadilakhir","Rajab","Syakban","Ramadan","Syawal","Zulkaidah","Zulhijah"},GM={"Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"};
 private ThemePalette theme;private int navy,background,surface,border,textPrimary,muted,emerald,gold;private LinearLayout root,grid;private TextView title,subTitle,nextName,nextTime,nextRemaining;private HijrahDate shownH;private YearMonth shownG;private LocalDate selected;private int correction;
 private android.content.SharedPreferences prefs(){return getSharedPreferences("settings",0);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(9),dp(6),dp(9),dp(6));v.setGravity(Gravity.CENTER_VERTICAL);return v;}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private GradientDrawable outlined(int c,int r){GradientDrawable g=bg(c,r);g.setStroke(dp(1),border);return g;}private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(11),dp(14),dp(11));c.setBackground(outlined(surface,16));return c;}private LinearLayout.LayoutParams margin(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(14),dp(8),dp(14),dp(4));return p;}
 @Override public void onCreate(Bundle b){super.onCreate(b);theme=ThemePalette.from(this);navy=theme.navy;background=theme.background;surface=theme.surface;border=theme.border;textPrimary=theme.textPrimary;muted=theme.muted;emerald=theme.accent;gold=theme.gold;theme.applySystemBars(this);correction=prefs().getInt("correction",0);today();build();render();IconUpdater.update(this);PrayerAlarmScheduler.update(this);askLocation();}@Override protected void onResume(){super.onResume();if(prefs().getBoolean("settings_changed",false)){prefs().edit().putBoolean("settings_changed",false).apply();recreate();}}
 private HijrahDate effectiveH(){return HijrahDate.from(SolarTime.effectiveCivilDate(this).plusDays(correction));}private boolean hijriMain(){return "hijri".equals(prefs().getString("main_calendar","hijri"));}private void today(){selected=SolarTime.effectiveCivilDate(this);shownH=effectiveH().with(ChronoField.DAY_OF_MONTH,1);shownG=YearMonth.from(selected);}
 private void build(){ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(background);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(background);scroll.addView(root);setContentView(scroll);LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setPadding(dp(18),dp(16),dp(12),dp(14));hero.setBackgroundColor(navy);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView brand=tv("\u263E  KALENDER HIJRIAH",12,gold);brand.setLetterSpacing(.08f);bar.addView(brand,new LinearLayout.LayoutParams(0,dp(42),1));TextView settings=tv("\u2699",23,Color.WHITE);settings.setGravity(Gravity.CENTER);settings.setContentDescription("Pengaturan");settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));bar.addView(settings,new LinearLayout.LayoutParams(dp(50),dp(42)));hero.addView(bar);title=tv("",26,Color.WHITE);title.setTypeface(null,Typeface.BOLD);hero.addView(title);subTitle=tv("",13,theme.heroSecondary);hero.addView(subTitle);root.addView(hero);
 LinearLayout next=new LinearLayout(this);next.setOrientation(LinearLayout.VERTICAL);next.setPadding(dp(15),dp(10),dp(15),dp(11));next.setBackground(bg(emerald,18));LinearLayout upper=new LinearLayout(this);upper.setGravity(Gravity.CENTER_VERTICAL);LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.VERTICAL);TextView label=tv("SALAT BERIKUTNYA",11,theme.onAccent);label.setAlpha(.86f);label.setPadding(0,0,0,dp(3));left.addView(label);nextName=tv("",20,theme.onAccent);nextName.setPadding(0,0,0,0);nextName.setTypeface(null,Typeface.BOLD);left.addView(nextName);upper.addView(left,new LinearLayout.LayoutParams(0,-2,1));nextTime=tv("",26,theme.onAccent);nextTime.setPadding(0,0,0,0);nextTime.setTypeface(null,Typeface.BOLD);upper.addView(nextTime);next.addView(upper);nextRemaining=tv("",11,theme.onAccent);nextRemaining.setAlpha(.86f);nextRemaining.setPadding(0,dp(3),0,0);next.addView(nextRemaining);LinearLayout.LayoutParams np=margin();np.setMargins(dp(14),dp(12),dp(14),dp(8));root.addView(next,np);
 LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(18),dp(4),dp(18),0);TextView prev=navButton("\u2039");prev.setOnClickListener(v->{move(-1);render();});TextView now=navButton("HARI INI");now.setTextSize(12);now.setOnClickListener(v->{today();render();});TextView nxt=navButton("\u203A");nxt.setOnClickListener(v->{move(1);render();});nav.addView(prev,new LinearLayout.LayoutParams(0,dp(46),1));nav.addView(now,new LinearLayout.LayoutParams(0,dp(46),2));nav.addView(nxt,new LinearLayout.LayoutParams(0,dp(46),1));root.addView(nav);grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);grid.setPadding(dp(12),0,dp(12),0);root.addView(grid);addPrayerCard();}
 private TextView navButton(String s){TextView v=tv(s,24,textPrimary);v.setGravity(Gravity.CENTER);v.setBackgroundColor(Color.TRANSPARENT);return v;}
 private void move(int n){if(hijriMain())shownH=shownH.plus(n,ChronoUnit.MONTHS).with(ChronoField.DAY_OF_MONTH,1);else shownG=shownG.plusMonths(n);}private void addPrayerCard(){LinearLayout c=card();LinearLayout head=new LinearLayout(this);TextView h=tv("Jadwal hari ini",13,textPrimary);h.setTypeface(null,Typeface.BOLD);head.addView(h,new LinearLayout.LayoutParams(0,-2,1));head.addView(tv(prefs().getBoolean("has_location",false)?"Lokasi perangkat":"Jakarta",11,muted));c.addView(head);PrayerTimes t=PrayerUtils.times(this,LocalDate.now());Date[] ds=PrayerUtils.dates(t);int[] indexes={0,2,3,4,5};LinearLayout row=new LinearLayout(this);for(int i:indexes){LinearLayout col=new LinearLayout(this);col.setOrientation(LinearLayout.VERTICAL);col.setGravity(Gravity.CENTER);TextView n=tv(PrayerUtils.NAMES[i],10,muted);n.setGravity(Gravity.CENTER);TextView tm=tv(PrayerUtils.format(ds[i]),12,textPrimary);tm.setTypeface(null,Typeface.BOLD);tm.setGravity(Gravity.CENTER);col.addView(n);col.addView(tm);row.addView(col,new LinearLayout.LayoutParams(0,-2,1));}c.addView(row);View divider=new View(this);divider.setBackgroundColor(border);LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(-1,dp(1));dl.setMargins(0,dp(8),0,0);c.addView(divider,dl);TextView q=tv("\u2301   Cari arah Kiblat",13,emerald);q.setGravity(Gravity.CENTER);q.setPadding(0,dp(12),0,dp(4));q.setOnClickListener(v->startActivity(new Intent(this,QiblaActivity.class)));c.addView(q);root.addView(c,margin());}
 private String hijri(HijrahDate h){return h.get(ChronoField.DAY_OF_MONTH)+" "+HM[h.get(ChronoField.MONTH_OF_YEAR)-1]+" "+h.get(ChronoField.YEAR)+" H";}private int offset(DayOfWeek d){return "sunday".equals(prefs().getString("week_start","friday"))?d.getValue()%7:(d.getValue()-5+7)%7;}
 private void render(){updateNextPrayer();grid.removeAllViews();String[] days="sunday".equals(prefs().getString("week_start","friday"))?new String[]{"Min","Sen","Sel","Rab","Kam","Jum","Sab"}:new String[]{"Jum","Sab","Min","Sen","Sel","Rab","Kam"};LinearLayout header=new LinearLayout(this);for(String d:days){TextView v=tv(d,11,emerald);v.setGravity(Gravity.CENTER);v.setTypeface(null,Typeface.BOLD);header.addView(v,new LinearLayout.LayoutParams(0,dp(30),1));}grid.addView(header);if(hijriMain())renderH();else renderG();}
 private void updateNextPrayer(){Date now=new Date(),chosen=null;String name="Subuh";PrayerTimes t=PrayerUtils.times(this,LocalDate.now());Date[] ds=PrayerUtils.dates(t);int[] ids={0,2,3,4,5};for(int i:ids)if(ds[i].after(now)){chosen=ds[i];name=PrayerUtils.NAMES[i];break;}if(chosen==null){PrayerTimes tomorrow=PrayerUtils.times(this,LocalDate.now().plusDays(1));chosen=tomorrow.fajr;}long minutes=Math.max(0,(chosen.getTime()-now.getTime())/60000);nextName.setText(name);nextTime.setText(PrayerUtils.format(chosen));nextRemaining.setText(minutes<60?minutes+" menit lagi":(minutes/60)+" jam "+(minutes%60)+" menit lagi");}
 private void renderH(){int m=shownH.get(ChronoField.MONTH_OF_YEAR),y=shownH.get(ChronoField.YEAR),count=(int)shownH.range(ChronoField.DAY_OF_MONTH).getMaximum();LocalDate first=LocalDate.from(shownH).minusDays(correction),last=LocalDate.from(shownH.with(ChronoField.DAY_OF_MONTH,count)).minusDays(correction);title.setText(HM[m-1]+" "+y+" H");subTitle.setText(first.getDayOfMonth()+" "+GM[first.getMonthValue()-1]+" – "+last.getDayOfMonth()+" "+GM[last.getMonthValue()-1]+" "+last.getYear());fill(count,offset(first.getDayOfWeek()),d->LocalDate.from(shownH.with(ChronoField.DAY_OF_MONTH,d)).minusDays(correction),true);}private void renderG(){LocalDate first=shownG.atDay(1),last=shownG.atEndOfMonth();title.setText(GM[shownG.getMonthValue()-1]+" "+shownG.getYear());subTitle.setText(hijri(HijrahDate.from(first.plusDays(correction)))+" – "+hijri(HijrahDate.from(last.plusDays(correction))));fill(shownG.lengthOfMonth(),offset(first.getDayOfWeek()),shownG::atDay,false);}private interface Maker{LocalDate get(int d);}
 private void fill(int count,int start,Maker make,boolean hPrimary){
  int cell=0,rows=(start+count+6)/7;
  for(int r=0;r<rows;r++){
   LinearLayout line=new LinearLayout(this);
   for(int col=0;col<7;col++,cell++){
    int d=cell-start+1;
    if(d<1||d>count){line.addView(new Space(this),new LinearLayout.LayoutParams(0,dp(42),1));continue;}
    LocalDate civil=make.get(d);HijrahDate h=HijrahDate.from(civil.plusDays(correction));
    boolean pick=civil.equals(selected),now=civil.equals(SolarTime.effectiveCivilDate(this));
    LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(0,dp(3),0,dp(3));
    if(pick)box.setBackground(bg(emerald,11));else if(now)box.setBackground(outlined(background,11));
    int a=hPrimary?h.get(ChronoField.DAY_OF_MONTH):civil.getDayOfMonth(),b=hPrimary?civil.getDayOfMonth():h.get(ChronoField.DAY_OF_MONTH);
    TextView primary=tv(String.valueOf(a),15,pick?theme.onAccent:textPrimary);primary.setPadding(0,0,0,0);primary.setIncludeFontPadding(false);primary.setGravity(Gravity.CENTER);primary.setTypeface(null,Typeface.BOLD);
    TextView secondary=tv(String.valueOf(b),9,pick?theme.onAccent:theme.accentSoft);secondary.setPadding(0,0,0,0);secondary.setIncludeFontPadding(false);secondary.setGravity(Gravity.CENTER);
    box.addView(primary,new LinearLayout.LayoutParams(-1,0,3));box.addView(secondary,new LinearLayout.LayoutParams(-1,0,2));
    box.setOnClickListener(v->{selected=civil;render();});line.addView(box,new LinearLayout.LayoutParams(0,dp(42),1));
   }
   grid.addView(line);
  }
 }
 private String moon(int d){if(d<=2)return"Bulan baru";if(d<=6)return"Sabit muda — terang di kanan";if(d<=9)return"Perbani awal";if(d<=13)return"Cembung awal";if(d<=16)return"Purnama";if(d<=20)return"Cembung akhir";if(d<=23)return"Perbani akhir";return"Sabit tua — terang di kiri";}
 private void askLocation(){if(!prefs().getBoolean("asked_location",false)){prefs().edit().putBoolean("asked_location",true).apply();new AlertDialog.Builder(this).setTitle("Gunakan lokasi saat ini?").setMessage("Lokasi diperlukan agar waktu salat, kiblat, dan pergantian tanggal saat Maghrib lebih sesuai. Data lokasi hanya disimpan di HP.").setPositiveButton("Izinkan",(d,w)->requestLocation()).setNegativeButton("Nanti",null).show();}}private void requestLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION},44);else refreshLocation();}@Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==44&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)refreshLocation();}private void refreshLocation(){try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);String provider=lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER)?LocationManager.NETWORK_PROVIDER:LocationManager.GPS_PROVIDER;lm.getCurrentLocation(provider,null,getMainExecutor(),this::saveLocation);}catch(Exception ignored){}}private void saveLocation(Location l){if(l==null)return;prefs().edit().putFloat("latitude",(float)l.getLatitude()).putFloat("longitude",(float)l.getLongitude()).putBoolean("has_location",true).apply();IconUpdater.update(this);PrayerAlarmScheduler.update(this);recreate();}
}
