package id.kalender.hijriah;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.hardware.*;import android.location.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.Locale;

public class QiblaActivity extends Activity implements SensorEventListener{
 private ThemePalette theme;private int navy,background,surface,border,textPrimary,muted,green;private LinearLayout body;private SensorManager sensors;private Sensor accel,magnet;private float[] gravity,field;private float azimuth,lastAzimuth=Float.NaN,movement;private int state;private Compass compass;private ProgressBar progress;private TextView gpsStatus;private double qibla;private final Handler locationHandler=new Handler(Looper.getMainLooper());private LocationManager activeLocationManager;private Location fallbackLocation,gpsPrevious;private boolean locationDelivered,gpsBearingReady;
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(8),dp(6),dp(8),dp(6));return v;}private android.graphics.drawable.GradientDrawable rounded(int color,int radius){android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 @Override public void onCreate(Bundle b){super.onCreate(b);theme=ThemePalette.from(this);navy=theme.navy;background=theme.background;surface=theme.surface;border=theme.border;textPrimary=theme.textPrimary;muted=theme.muted;green=theme.accent;theme.applySystemBars(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(background);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(12),0,dp(12),0);bar.setBackgroundColor(navy);TextView back=tv("\u2039",30,Color.WHITE);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());bar.addView(back,new LinearLayout.LayoutParams(dp(46),dp(58)));bar.addView(tv("Arah Kiblat",19,Color.WHITE),new LinearLayout.LayoutParams(0,dp(58),1));root.addView(bar);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setGravity(Gravity.CENTER_HORIZONTAL);body.setPadding(dp(24),dp(34),dp(24),dp(24));root.addView(body,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);sensors=(SensorManager)getSystemService(SENSOR_SERVICE);accel=sensors.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);magnet=sensors.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);showPrerequisite();}
 private boolean locationEnabled(){LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);return Build.VERSION.SDK_INT>=28?lm.isLocationEnabled():lm.isProviderEnabled(LocationManager.GPS_PROVIDER)||lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER);}
 private void showPrerequisite(){state=0;body.removeAllViews();TextView pin=tv("⌖",62,green);pin.setGravity(Gravity.CENTER);body.addView(pin,new LinearLayout.LayoutParams(-1,dp(100)));TextView title=tv("Aktifkan lokasi",24,textPrimary);title.setGravity(Gravity.CENTER);title.setTypeface(null,Typeface.BOLD);body.addView(title);TextView note=tv("Arah Kiblat dihitung dari posisi Anda. Lokasi harus aktif dan diperbarui sebelum kompas dikalibrasi.",13,muted);note.setGravity(Gravity.CENTER);body.addView(note);TextView button=tv(locationEnabled()?"Gunakan lokasi saat ini":"Buka pengaturan lokasi",13,Color.WHITE);button.setGravity(Gravity.CENTER);button.setBackground(rounded(green,11));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(220),dp(46));p.setMargins(0,dp(24),0,0);body.addView(button,p);button.setOnClickListener(v->{if(!locationEnabled())startActivity(new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS));else requestLocation();});}
 private void requestLocation(){
  if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},51);return;}
  state=1;locationDelivered=false;fallbackLocation=null;body.removeAllViews();ProgressBar wait=new ProgressBar(this);body.addView(wait,new LinearLayout.LayoutParams(-1,dp(70)));TextView label=tv("Mencari lokasi GPS dan jaringan…",16,textPrimary);label.setGravity(Gravity.CENTER);body.addView(label);TextView note=tv("Pastikan Lokasi aktif. Proses dapat memerlukan beberapa detik.",12,muted);note.setGravity(Gravity.CENTER);body.addView(note);
  try{
   activeLocationManager=(LocationManager)getSystemService(LOCATION_SERVICE);
   android.content.SharedPreferences saved=getSharedPreferences("settings",0);if(saved.getBoolean("has_location",false)){Location stored=new Location("tersimpan");stored.setLatitude(saved.getFloat("latitude",-6.2f));stored.setLongitude(saved.getFloat("longitude",106.8167f));stored.setAccuracy(saved.getFloat("location_accuracy",5000));stored.setTime(saved.getLong("location_time",0));fallbackLocation=stored;}
   requestProvider(LocationManager.NETWORK_PROVIDER);requestProvider(LocationManager.GPS_PROVIDER);
   long age=fallbackLocation==null?Long.MAX_VALUE:System.currentTimeMillis()-fallbackLocation.getTime();if(fallbackLocation!=null&&fallbackLocation.getTime()>0&&age<1800000L){Location recent=fallbackLocation;locationHandler.post(()->locationReady(recent));return;}
   locationHandler.postDelayed(()->{if(!locationDelivered&&fallbackLocation!=null)locationReady(fallbackLocation);},2500);
   locationHandler.postDelayed(()->{if(locationDelivered)return;Toast.makeText(this,"Lokasi belum tersedia. Pastikan mode Lokasi aktif, lalu coba lagi.",Toast.LENGTH_LONG).show();showPrerequisite();},8000);
  }catch(Exception e){Toast.makeText(this,"Layanan lokasi tidak dapat diakses",Toast.LENGTH_LONG).show();showPrerequisite();}
 }
 private void requestProvider(String provider){
  try{
   if(!activeLocationManager.isProviderEnabled(provider))return;
   Location last=activeLocationManager.getLastKnownLocation(provider);if(last!=null&&System.currentTimeMillis()-last.getTime()<21600000L&&(fallbackLocation==null||last.getTime()>fallbackLocation.getTime()))fallbackLocation=last;
   activeLocationManager.requestLocationUpdates(provider,1000,1f,locationListener,Looper.getMainLooper());
   if(Build.VERSION.SDK_INT>=30)activeLocationManager.getCurrentLocation(provider,null,getMainExecutor(),l->{if(l!=null)locationReady(l);});
  }catch(Exception ignored){}
 }
 private final LocationListener locationListener=new LocationListener(){
  @Override public void onLocationChanged(Location location){if(state==4)updateGpsBearing(location);else locationReady(location);}
  @Override public void onProviderEnabled(String provider){}
  @Override public void onProviderDisabled(String provider){}
  @Override public void onStatusChanged(String provider,int status,Bundle extras){}
 };
 private void locationReady(Location l){
  if(l==null||locationDelivered)return;locationDelivered=true;locationHandler.removeCallbacksAndMessages(null);try{if(activeLocationManager!=null)activeLocationManager.removeUpdates(locationListener);}catch(Exception ignored){}
  getSharedPreferences("settings",0).edit().putFloat("latitude",(float)l.getLatitude()).putFloat("longitude",(float)l.getLongitude()).putFloat("location_accuracy",l.hasAccuracy()?l.getAccuracy():-1).putLong("location_time",l.getTime()>0?l.getTime():System.currentTimeMillis()).putBoolean("has_location",true).apply();qibla=PrayerUtils.qibla(this);if(magnet==null)showGpsGuide();else showCalibration();
 }
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==51&&(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED))requestLocation();else showPrerequisite();}
 @Override protected void onDestroy(){super.onDestroy();locationHandler.removeCallbacksAndMessages(null);try{if(activeLocationManager!=null)activeLocationManager.removeUpdates(locationListener);}catch(Exception ignored){}}
 private void showCalibration(){state=2;movement=0;lastAzimuth=Float.NaN;body.removeAllViews();TextView spin=tv("↻",72,green);spin.setGravity(Gravity.CENTER);body.addView(spin,new LinearLayout.LayoutParams(-1,dp(110)));TextView title=tv("Kalibrasi kompas",23,textPrimary);title.setGravity(Gravity.CENTER);title.setTypeface(null,Typeface.BOLD);body.addView(title);TextView instruction=tv("Pegang ponsel lalu putar pergelangan tangan membentuk gerakan melingkar atau angka 8 sebanyak beberapa kali.",14,textPrimary);instruction.setGravity(Gravity.CENTER);body.addView(instruction);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(540);progress.setProgress(0);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(14));pp.setMargins(dp(16),dp(24),dp(16),dp(8));body.addView(progress,pp);TextView note=tv("Jauhkan ponsel dari logam dan perangkat elektronik.",12,muted);note.setGravity(Gravity.CENTER);body.addView(note);if(accel==null||magnet==null){note.setText("Sensor kompas tidak tersedia pada perangkat ini.");progress.setVisibility(View.GONE);}}
 private void showGpsGuide(){state=4;gpsBearingReady=false;gpsPrevious=null;azimuth=0;body.removeAllViews();TextView icon=tv("⌖",58,green);icon.setGravity(Gravity.CENTER);body.addView(icon,new LinearLayout.LayoutParams(-1,dp(84)));TextView title=tv("Panduan Kiblat dengan GPS",22,textPrimary);title.setGravity(Gravity.CENTER);title.setTypeface(null,Typeface.BOLD);body.addView(title);TextView why=tv("Ponsel ini tidak memiliki sensor kompas magnetik. Arah akan dibaca dari gerakan GPS.",13,muted);why.setGravity(Gravity.CENTER);body.addView(why);compass=new Compass(this);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(245),dp(245));cp.setMargins(0,dp(14),0,dp(12));body.addView(compass,cp);TextView instruction=tv("Di tempat terbuka, pegang ponsel dengan bagian atas menghadap ke depan lalu berjalan lurus sekitar 10–15 meter.",14,textPrimary);instruction.setGravity(Gravity.CENTER);instruction.setTypeface(null,Typeface.BOLD);body.addView(instruction);gpsStatus=tv("Menunggu arah gerakan GPS…",12,green);gpsStatus.setGravity(Gravity.CENTER);body.addView(gpsStatus);TextView bearing=tv(directionText()+" dari Utara",12,muted);bearing.setGravity(Gravity.CENTER);body.addView(bearing);TextView retry=tv("↻  Mulai ulang pembacaan GPS",13,green);retry.setGravity(Gravity.CENTER);retry.setOnClickListener(v->{gpsBearingReady=false;gpsPrevious=null;if(compass!=null)compass.invalidate();startGpsBearing();});LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(48));rp.setMargins(0,dp(8),0,0);body.addView(retry,rp);startGpsBearing();}
 private void startGpsBearing(){try{if(activeLocationManager==null)activeLocationManager=(LocationManager)getSystemService(LOCATION_SERVICE);activeLocationManager.removeUpdates(locationListener);boolean requested=false;String[] providers={LocationManager.GPS_PROVIDER,LocationManager.NETWORK_PROVIDER};for(String provider:providers)if(activeLocationManager.isProviderEnabled(provider)){activeLocationManager.requestLocationUpdates(provider,1000,2f,locationListener,Looper.getMainLooper());requested=true;}if(gpsStatus!=null)gpsStatus.setText(requested?"Berjalan lurus agar arah terbaca…":"Aktifkan GPS lalu coba lagi.");}catch(Exception e){if(gpsStatus!=null)gpsStatus.setText("GPS belum dapat diakses.");}}
 private void updateGpsBearing(Location location){if(location==null)return;if(location.hasAccuracy()&&location.getAccuracy()>80){if(gpsStatus!=null)gpsStatus.setText("Menunggu akurasi GPS yang lebih baik…");return;}Float heading=null;if(location.hasBearing()&&(!location.hasSpeed()||location.getSpeed()>.25f))heading=location.getBearing();else if(gpsPrevious!=null&&gpsPrevious.distanceTo(location)>=3f)heading=gpsPrevious.bearingTo(location);gpsPrevious=location;if(heading==null)return;azimuth=(heading%360+360)%360;gpsBearingReady=true;if(compass!=null)compass.invalidate();if(gpsStatus!=null)gpsStatus.setText(String.format(Locale.US,"Arah gerak terbaca %.0f°. Ikuti panah Kiblat.",azimuth));}
 private void showCompass(){state=3;body.removeAllViews();TextView bearing=tv(directionText(),25,textPrimary);bearing.setGravity(Gravity.CENTER);body.addView(bearing);compass=new Compass(this);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(265),dp(265));cp.setMargins(0,dp(16),0,dp(22));body.addView(compass,cp);TextView instruction=tv("Arahkan bagian atas ponsel mengikuti panah",14,textPrimary);instruction.setTypeface(null,Typeface.BOLD);instruction.setGravity(Gravity.CENTER);body.addView(instruction);TextView note=tv("Lokasi dan kompas sudah dikalibrasi.",12,muted);note.setGravity(Gravity.CENTER);body.addView(note);TextView refresh=tv("↻  Kalibrasi ulang kompas",13,green);refresh.setGravity(Gravity.CENTER);refresh.setOnClickListener(v->showCalibration());LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(48));rp.setMargins(0,dp(14),0,0);body.addView(refresh,rp);}
 private String directionText(){String d=qibla>=292.5&&qibla<337.5?"Barat Laut":qibla>=247.5?"Barat":"Arah Kiblat";return String.format(Locale.US,"%.0f°  %s",qibla,d);}@Override protected void onResume(){super.onResume();if(accel!=null)sensors.registerListener(this,accel,SensorManager.SENSOR_DELAY_GAME);if(magnet!=null)sensors.registerListener(this,magnet,SensorManager.SENSOR_DELAY_GAME);if(state==0&&locationEnabled()&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED)showPrerequisite();else if(state==4)startGpsBearing();}@Override protected void onPause(){super.onPause();sensors.unregisterListener(this);if(state==4)try{if(activeLocationManager!=null)activeLocationManager.removeUpdates(locationListener);}catch(Exception ignored){}}@Override public void onAccuracyChanged(Sensor s,int a){}
 @Override public void onSensorChanged(SensorEvent e){if(e.sensor.getType()==Sensor.TYPE_ACCELEROMETER)gravity=e.values.clone();else if(e.sensor.getType()==Sensor.TYPE_MAGNETIC_FIELD)field=e.values.clone();if(gravity==null||field==null)return;float[] r=new float[9],i=new float[9],o=new float[3];if(!SensorManager.getRotationMatrix(r,i,gravity,field))return;SensorManager.getOrientation(r,o);azimuth=(float)Math.toDegrees(o[0]);if(state==2){if(!Float.isNaN(lastAzimuth)){float delta=Math.abs(azimuth-lastAzimuth);if(delta>180)delta=360-delta;if(delta>1&&delta<45){movement+=delta;if(progress!=null)progress.setProgress((int)Math.min(540,movement));if(movement>=540)showCompass();}}lastAzimuth=azimuth;}else if(state==3&&compass!=null)compass.invalidate();}
 private class Compass extends View{Paint p=new Paint(1);Compass(Activity c){super(c);}protected void onDraw(Canvas c){float x=getWidth()/2f,y=getHeight()/2f,r=Math.min(x,y)-dp(9);p.setStyle(Paint.Style.FILL);p.setColor(surface);c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2));p.setColor(border);c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(13));p.setColor(green);c.drawText(state==4?"ARAH JALAN":"U",x,dp(28),p);if(state==4&&!gpsBearingReady){p.setTextSize(dp(12));p.setColor(muted);c.drawText("Menunggu GPS",x,y-dp(32),p);}else{c.save();c.rotate((float)(qibla-azimuth),x,y);Path arrow=new Path();arrow.moveTo(x,dp(34));arrow.lineTo(x-dp(15),y);arrow.lineTo(x,y-dp(8));arrow.lineTo(x+dp(15),y);arrow.close();p.setColor(green);c.drawPath(arrow,p);c.restore();}p.setColor(Color.rgb(17,17,17));c.drawRect(x-dp(23),y-dp(23),x+dp(23),y+dp(23),p);p.setColor(Color.rgb(244,201,93));c.drawRect(x-dp(23),y+dp(14),x+dp(23),y+dp(23),p);}}
}
