package id.kalender.hijriah;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.media.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;

public class SettingsActivity extends Activity{
 private ThemePalette theme;private int navy,background,surface,surfaceSoft,border,textPrimary,muted,green;private android.content.SharedPreferences prefs;private LinearLayout body;private TextView correction,location;private MediaPlayer previewPlayer;
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(2),dp(7),dp(2),dp(7));v.setGravity(Gravity.CENTER_VERTICAL);return v;}private GradientDrawable rounded(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("settings",0);theme=ThemePalette.from(this);navy=theme.navy;background=theme.background;surface=theme.surface;surfaceSoft=theme.surfaceSoft;border=theme.border;textPrimary=theme.textPrimary;muted=theme.muted;green=theme.accent;theme.applySystemBars(this);ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(background);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(background);scroll.addView(root);setContentView(scroll);LinearLayout appbar=new LinearLayout(this);appbar.setGravity(Gravity.CENTER_VERTICAL);appbar.setPadding(dp(12),0,dp(12),0);appbar.setBackgroundColor(navy);TextView back=tv("\u2039",30,Color.WHITE);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());appbar.addView(back,new LinearLayout.LayoutParams(dp(46),dp(58)));TextView title=tv("Pengaturan",19,Color.WHITE);appbar.addView(title,new LinearLayout.LayoutParams(0,dp(58),1));root.addView(appbar);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(7),dp(16),dp(22));root.addView(body);
 section("TAMPILAN KALENDER");themeRow();choice("Hari pertama dalam sepekan",null,new String[]{"Jumat","Minggu"},new String[]{"friday","sunday"},"week_start");choice("Kalender utama","Kalender lainnya tetap tampil sebagai tanggal sekunder",new String[]{"Hijriah","Masehi"},new String[]{"hijri","gregorian"},"main_calendar");
 section("JADWAL SALAT");alarmRow();methodRow();prayerCorrectionRow();locationRow();section("PENYESUAIAN");correctionRow();infoRow();
 }
 private void themeRow(){
  LinearLayout r=row();TextView title=tv("Tema aplikasi",14,textPrimary);title.setTypeface(null,Typeface.BOLD);r.addView(title);r.addView(tv("Malam Zamrud  •  Fajar Safir  •  Zaitun Pasir",11,muted));
  LinearLayout group=new LinearLayout(this);group.setPadding(dp(4),dp(4),dp(4),dp(4));group.setBackground(rounded(surfaceSoft,12));String current=prefs.getString("app_theme","zamrud");
  String[] names={"Zamrud","Safir","Zaitun"},values={"zamrud","safir","zaitun"};TextView[] buttons=new TextView[3];
  for(int i=0;i<3;i++){final int pos=i;boolean selected=values[i].equals(current);buttons[i]=tv(names[i],11,selected?theme.onAccent:textPrimary);buttons[i].setGravity(Gravity.CENTER);buttons[i].setBackground(rounded(selected?green:Color.TRANSPARENT,9));buttons[i].setOnClickListener(v->{if(values[pos].equals(prefs.getString("app_theme","zamrud")))return;prefs.edit().putString("app_theme",values[pos]).putBoolean("settings_changed",true).apply();IconUpdater.update(this);recreate();});group.addView(buttons[i],new LinearLayout.LayoutParams(0,dp(42),1));}
  LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,-2);gp.setMargins(0,dp(5),0,0);r.addView(group,gp);addRow(r);
 }
 private void section(String s){TextView v=tv(s,11,green);v.setLetterSpacing(.08f);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(2),dp(13),0,0);body.addView(v,p);}
 private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(2),dp(8),dp(2),dp(10));r.setBackgroundColor(Color.TRANSPARENT);return r;}private void addRow(LinearLayout r){body.addView(r,new LinearLayout.LayoutParams(-1,-2));View divider=new View(this);divider.setBackgroundColor(border);body.addView(divider,new LinearLayout.LayoutParams(-1,dp(1)));}
 private void choice(String title,String note,String[] names,String[] values,String key){LinearLayout r=row();TextView t=tv(title,14,textPrimary);t.setTypeface(null,Typeface.BOLD);r.addView(t);LinearLayout group=new LinearLayout(this);group.setPadding(dp(4),dp(4),dp(4),dp(4));group.setBackground(rounded(surfaceSoft,12));String current=prefs.getString(key,values[0]);TextView[] buttons=new TextView[2];for(int i=0;i<2;i++){final int pos=i;boolean selected=values[i].equals(current);buttons[i]=tv(names[i],12,selected?theme.onAccent:textPrimary);buttons[i].setGravity(Gravity.CENTER);buttons[i].setBackground(rounded(selected?green:Color.TRANSPARENT,9));buttons[i].setOnClickListener(v->{prefs.edit().putString(key,values[pos]).putBoolean("settings_changed",true).apply();if("main_calendar".equals(key))IconUpdater.update(this);for(int j=0;j<2;j++){buttons[j].setBackground(rounded(j==pos?green:Color.TRANSPARENT,9));buttons[j].setTextColor(j==pos?theme.onAccent:textPrimary);}});group.addView(buttons[i],new LinearLayout.LayoutParams(0,dp(40),1));}r.addView(group);if(note!=null)r.addView(tv(note,11,muted));addRow(r);}
 private void alarmRow(){
  LinearLayout r=row(),top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=tv("Alarm waktu salat",14,textPrimary);title.setTypeface(null,Typeface.BOLD);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));ToggleView sw=new ToggleView();sw.setChecked(prefs.getBoolean("alarm_enabled",false));top.addView(sw,new LinearLayout.LayoutParams(dp(44),dp(25)));r.addView(top);
  RadioGroup sounds=new RadioGroup(this);RadioButton beautiful=new RadioButton(this);beautiful.setText("Beautiful Adhan (CC0)");RadioButton doha=new RadioButton(this);doha.setText("Adzan Doha (Public Domain)");RadioButton local=new RadioButton(this);local.setText("Adzan dari file lokal");RadioButton device=new RadioButton(this);device.setText("Nada bawaan ponsel");RadioButton[] soundButtons={beautiful,doha,local,device};for(RadioButton button:soundButtons){button.setTextColor(textPrimary);if(Build.VERSION.SDK_INT>=21)button.setButtonTintList(new android.content.res.ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{green,muted}));sounds.addView(button);}
  String mode=prefs.getString("sound_mode","device");beautiful.setChecked("builtin_beautiful".equals(mode));doha.setChecked("builtin_doha".equals(mode));local.setChecked("local".equals(mode));device.setChecked("device".equals(mode));
  beautiful.setOnClickListener(v->saveSoundMode("builtin_beautiful"));doha.setOnClickListener(v->saveSoundMode("builtin_doha"));local.setOnClickListener(v->pickAdhan());device.setOnClickListener(v->pickRingtone());
  LinearLayout volumeBox=new LinearLayout(this);volumeBox.setOrientation(LinearLayout.VERTICAL);volumeBox.setPadding(dp(4),dp(9),dp(4),dp(5));LinearLayout volumeTop=new LinearLayout(this);volumeTop.setGravity(Gravity.CENTER_VERTICAL);TextView volumeTitle=tv("Volume adzan aplikasi",12,textPrimary);volumeTitle.setTypeface(null,Typeface.BOLD);TextView volumeValue=tv("",12,green);volumeTop.addView(volumeTitle,new LinearLayout.LayoutParams(0,-2,1));volumeTop.addView(volumeValue);volumeBox.addView(volumeTop);SeekBar volume=new SeekBar(this);volume.setMax(100);volume.setProgress(prefs.getInt("adhan_volume",80));volumeValue.setText(volume.getProgress()+"%");volume.setProgressTintList(android.content.res.ColorStateList.valueOf(green));volume.setThumbTintList(android.content.res.ColorStateList.valueOf(green));volume.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar bar,int progress,boolean fromUser){volumeValue.setText(progress+"%");prefs.edit().putInt("adhan_volume",progress).apply();if(previewPlayer!=null){float level=progress/100f;previewPlayer.setVolume(level,level);}}public void onStartTrackingTouch(SeekBar bar){}public void onStopTrackingTouch(SeekBar bar){previewSelectedSound();}});volumeBox.addView(volume);volumeBox.addView(tv("Khusus aplikasi ini; tidak mengubah volume alarm atau media ponsel.",10,muted));sounds.addView(volumeBox);
  TextView license=tv("Sumber dan lisensi audio ›",11,green);license.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Audio adzan terbuka").setMessage("Beautiful Adhan — Adam-synagda, Wikimedia Commons, CC0 1.0.\n\nAdzan Doha — Internet Archive, Public Domain Mark 1.0.\n\nTautan lengkap tercantum dalam informasi lisensi aplikasi.").setPositiveButton("Tutup",null).show());sounds.addView(license);
  sounds.setVisibility(sw.isChecked()?View.VISIBLE:View.GONE);sw.setOnClickListener(v->{boolean on=!sw.isChecked();sw.setChecked(on);sounds.setVisibility(on?View.VISIBLE:View.GONE);prefs.edit().putBoolean("alarm_enabled",on).putBoolean("settings_changed",true).apply();if(on)requestNotification();PrayerAlarmScheduler.update(this);});r.addView(sounds);addRow(r);
 }
 private void saveSoundMode(String mode){prefs.edit().putString("sound_mode",mode).apply();PrayerAlarmScheduler.update(this);previewSelectedSound();}
 private void previewSelectedSound(){stopPreview();try{previewPlayer=new MediaPlayer();previewPlayer.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build());previewPlayer.setDataSource(this,AdhanAudio.soundUri(this));float level=AdhanAudio.volume(this);previewPlayer.setVolume(level,level);previewPlayer.setOnPreparedListener(MediaPlayer::start);previewPlayer.setOnCompletionListener(mp->stopPreview());previewPlayer.setOnErrorListener((mp,what,extra)->{stopPreview();Toast.makeText(this,"Suara tidak dapat diputar",Toast.LENGTH_SHORT).show();return true;});previewPlayer.prepareAsync();}catch(Exception e){stopPreview();Toast.makeText(this,"Suara tidak dapat diputar",Toast.LENGTH_SHORT).show();}}
 private void stopPreview(){if(previewPlayer!=null){try{previewPlayer.stop();}catch(Exception ignored){}previewPlayer.release();previewPlayer=null;}}
 private void methodRow(){LinearLayout r=row(),top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView t=tv("Sumber perhitungan",14,textPrimary);t.setTypeface(null,Typeface.BOLD);top.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView selected=tv(PrayerUtils.methodLabel(this)+"  ›",12,green);top.addView(selected);r.addView(top);r.addView(tv("Pilih metode perhitungan jadwal salat",11,muted));String[] labels={"Kemenag RI (disarankan)","Muslim World League","Umm al-Qura","ISNA","Singapore"},values={"KEMENAG","MWL","UMM","ISNA","SINGAPORE"};r.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Sumber perhitungan").setSingleChoiceItems(labels,indexOf(values,prefs.getString("prayer_method","KEMENAG")),(dialog,which)->{prefs.edit().putString("prayer_method",values[which]).putBoolean("settings_changed",true).apply();selected.setText(labels[which].replace(" (disarankan)","")+"  ›");PrayerAlarmScheduler.update(this);dialog.dismiss();}).show());addRow(r);}
 private int indexOf(String[] values,String value){for(int i=0;i<values.length;i++)if(values[i].equals(value))return i;return 0;}
 private void prayerCorrectionRow(){LinearLayout r=row();TextView title=tv("Koreksi waktu salat",14,textPrimary);title.setTypeface(null,Typeface.BOLD);r.addView(title);r.addView(tv("Atur masing-masing waktu dari −5 sampai +5 menit",11,muted));String[] names={"Subuh","Zuhur","Asar","Maghrib","Isya"},keys={"adjust_fajr","adjust_dhuhr","adjust_asr","adjust_maghrib","adjust_isha"};for(int i=0;i<names.length;i++){LinearLayout item=new LinearLayout(this);item.setGravity(Gravity.CENTER_VERTICAL);TextView name=tv(names[i],12,textPrimary);item.addView(name,new LinearLayout.LayoutParams(0,dp(36),1));TextView minus=smallButton("−"),value=tv("",12,textPrimary),plus=smallButton("+");value.setGravity(Gravity.CENTER);final String key=keys[i];setMinuteText(value,prefs.getInt(key,0));minus.setOnClickListener(v->changePrayerMinute(key,-1,value));plus.setOnClickListener(v->changePrayerMinute(key,1,value));item.addView(minus,new LinearLayout.LayoutParams(dp(32),dp(32)));item.addView(value,new LinearLayout.LayoutParams(dp(72),dp(32)));item.addView(plus,new LinearLayout.LayoutParams(dp(32),dp(32)));r.addView(item);}addRow(r);}
 private void changePrayerMinute(String key,int delta,TextView value){int n=Math.max(-5,Math.min(5,prefs.getInt(key,0)+delta));prefs.edit().putInt(key,n).putBoolean("settings_changed",true).apply();setMinuteText(value,n);PrayerAlarmScheduler.update(this);}private void setMinuteText(TextView value,int n){value.setText((n>0?"+":"")+n+" menit");}
 private void locationRow(){LinearLayout r=row(),top=new LinearLayout(this);TextView t=tv("Lokasi",14,textPrimary);t.setTypeface(null,Typeface.BOLD);top.addView(t,new LinearLayout.LayoutParams(0,-2,1));location=tv(prefs.getBoolean("has_location",false)?"Lokasi perangkat":"Jakarta",13,textPrimary);top.addView(location);r.addView(top);r.addView(tv("Untuk jadwal salat, Maghrib, dan arah Kiblat",11,muted));TextView button=tv("Perbarui lokasi saat ini",12,Color.WHITE);button.setGravity(Gravity.CENTER);button.setBackground(rounded(green,10));button.setOnClickListener(v->requestLocation());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(190),dp(38));bp.setMargins(0,dp(7),0,0);r.addView(button,bp);addRow(r);}
 private void correctionRow(){LinearLayout r=row(),top=new LinearLayout(this);TextView t=tv("Koreksi tanggal Hijriah",14,textPrimary);t.setTypeface(null,Typeface.BOLD);top.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView minus=smallButton("−"),plus=smallButton("+");correction=tv("",12,textPrimary);correction.setGravity(Gravity.CENTER);minus.setOnClickListener(v->change(-1));plus.setOnClickListener(v->change(1));top.addView(minus,new LinearLayout.LayoutParams(dp(34),dp(34)));top.addView(correction,new LinearLayout.LayoutParams(dp(62),dp(34)));top.addView(plus,new LinearLayout.LayoutParams(dp(34),dp(34)));r.addView(top);updateCorrection();addRow(r);}private TextView smallButton(String s){TextView v=tv(s,17,textPrimary);v.setGravity(Gravity.CENTER);GradientDrawable d=rounded(Color.TRANSPARENT,8);d.setStroke(dp(1),border);v.setBackground(d);return v;}
 private void infoRow(){LinearLayout r=row();TextView summary=tv("▶  Info pergantian hari",13,green),copy=tv("Tanggal Hijriah dan fase bulan pada ikon berganti saat Maghrib berdasarkan lokasi perangkat. Jika kalender utama Masehi, angka ikonnya berganti pukul 00.00.",11,muted);copy.setVisibility(View.GONE);summary.setOnClickListener(v->{boolean show=copy.getVisibility()!=View.VISIBLE;copy.setVisibility(show?View.VISIBLE:View.GONE);summary.setText(show?"▼  Info pergantian hari":"▶  Info pergantian hari");});r.addView(summary);r.addView(copy);addRow(r);}
 private void change(int d){int n=Math.max(-2,Math.min(2,prefs.getInt("correction",0)+d));prefs.edit().putInt("correction",n).putBoolean("settings_changed",true).apply();updateCorrection();IconUpdater.update(this);}private void updateCorrection(){int n=prefs.getInt("correction",0);correction.setText((n>0?"+":"")+n+" hari");}
 private void pickAdhan(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("audio/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,91);}private void pickRingtone(){Intent i=new Intent(RingtoneManager.ACTION_RINGTONE_PICKER);i.putExtra(RingtoneManager.EXTRA_RINGTONE_TYPE,RingtoneManager.TYPE_ALARM);startActivityForResult(i,92);}
 private void requestLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION},44);else refreshLocation();}@Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==44&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)refreshLocation();}private void refreshLocation(){try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);String provider=lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER)?LocationManager.NETWORK_PROVIDER:LocationManager.GPS_PROVIDER;lm.getCurrentLocation(provider,null,getMainExecutor(),this::save);}catch(Exception e){Toast.makeText(this,"Lokasi belum tersedia",Toast.LENGTH_LONG).show();}}private void save(Location l){if(l==null)return;prefs.edit().putFloat("latitude",(float)l.getLatitude()).putFloat("longitude",(float)l.getLongitude()).putFloat("location_accuracy",l.hasAccuracy()?l.getAccuracy():-1).putLong("location_time",l.getTime()>0?l.getTime():System.currentTimeMillis()).putBoolean("has_location",true).putBoolean("settings_changed",true).apply();location.setText("Lokasi perangkat");IconUpdater.update(this);PrayerAlarmScheduler.update(this);}
 private void requestNotification(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},45);}@Override protected void onActivityResult(int r,int code,Intent data){super.onActivityResult(r,code,data);if(code!=RESULT_OK||data==null)return;if(r==91&&data.getData()!=null){Uri u=data.getData();getContentResolver().takePersistableUriPermission(u,data.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION);prefs.edit().putString("adhan_uri",u.toString()).putString("sound_mode","local").apply();}if(r==92){Uri u=data.getParcelableExtra(RingtoneManager.EXTRA_RINGTONE_PICKED_URI);if(u!=null)prefs.edit().putString("ringtone_uri",u.toString()).putString("sound_mode","device").apply();}PrayerAlarmScheduler.update(this);previewSelectedSound();}
 @Override protected void onStop(){stopPreview();super.onStop();}
 private class ToggleView extends View{
  private boolean checked;private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);
  ToggleView(){super(SettingsActivity.this);setClickable(true);}
  boolean isChecked(){return checked;}
  void setChecked(boolean value){checked=value;invalidate();}
  @Override protected void onDraw(Canvas c){super.onDraw(c);float h=getHeight(),w=getWidth(),r=h/2f;paint.setColor(checked?green:border);c.drawRoundRect(0,0,w,h,r,r,paint);paint.setColor(Color.WHITE);float knob=h*.38f;float x=checked?w-r:r;c.drawCircle(x,r,knob,paint);}
 }
}
